### ISSUE TITLE
No ember-try configuration found

### ISSUE THREAD

**Issue by henrymazza** [ember-cli/ember-try#216]
I'm getting this error:

```
No ember-try configuration found. Please see the README for configuration options
``` 

`ember-try` isn't finding the default configuration? Any Idea? I copied and pasted the README example to the designated folder and still the same thing.

```
ember-cli: 3.3.0
node: 8.11.3
os: darwin x64
```

PS: Above error's stack trace here
```
=================================================================================

ENV Summary:

  TIME: Thu Nov 08 2018 17:19:22 GMT-0200 (-02)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node@8/8.11.3_1/bin/node
  - /usr/local/bin/ember
  - try:config
  EXEC_PATH: /usr/local/Cellar/node@8/8.11.3_1/bin/node
  TMPDIR: /var/folders/cg/w_5kw26j063fymlnspb2wgqc0000gq/T
  SHELL: /bin/zsh
  PATH:
  - ./bin
  - ~/bin
  - /usr/local/opt/icu4c/sbin
  - /usr/local/opt/icu4c/sbin
  - /usr/local/opt/gettext/bin
  - /Users/HMz/.rbenv/bin
  - /usr/local/opt/gnu-sed/libexec/gnubin
  - /usr/local/opt/coreutils/libexec/gnubin
  - /usr/local/opt/node@8/bin
  - /usr/local/opt/icu4c/sbin
  - /usr/local/opt/icu4c/bin
  - /usr/local/opt/postgresql@9.5/bin
  - /Users/HMz/bin
  - /usr/local/sbin
  - /usr/local/share/npm/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  PLATFORM: darwin x64
  FREEMEM: 65712128
  TOTALMEM: 8589934592
  UPTIME: 161875
  LOADAVG: 2.67626953125,3.26708984375,3.3642578125
  CPUS:
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: No ember-try configuration found. Please see the README for configuration options
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: No ember-try configuration found. Please see the README for configuration options
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: No ember-try configuration found. Please see the README for configuration options
    at RSVP.resolve.then (/Users/HMz/Development/uni-fe/node_modules/ember-try/lib/utils/config.js:41:26)
    at tryCatcher (/Users/HMz/Development/uni-fe/node_modules/ember-try/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/HMz/Development/uni-fe/node_modules/ember-try/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/HMz/Development/uni-fe/node_modules/ember-try/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/HMz/Development/uni-fe/node_modules/ember-try/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


=================================================================================
```

**Comment by bracke** [comment]
I also have get this.

This is with ember-try installed today.
