### ISSUE TITLE
ember try is grabbing more than release/beta

### ISSUE THREAD

**Issue by EWhite613** [ember-cli/ember-try#72]
When executing `ember try:one ember-release --- ember test` or `ember try:one ember-beta --- ember test`. Try is grabbing more than the release/beta. Ember release using `2.4.4+0947bfc3` (https://github.com/emberjs/ember.js/commits/0947bfc3), and Ember beta using `2.5.0-beta.4+2841986d` (https://github.com/emberjs/ember.js/commits/2841986d).

Which as result causes this error:

> Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at _warnIfUsingStrippedFeatureFlags (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:1529:25)
    at /localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:1547:5
    at internalRequire (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:98:16)
    at requireModule (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:44:14)
    at /localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:20781:1
    at Object.<anonymous> (/localdisk/workspace/ember-frost-core/bower_components/ember/ember-template-compiler.js:20784:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Class.module.exports.included (/localdisk/workspace/ember-frost-core/node_modules/ember-cli-htmlbars-inline-precompile/index.js:17:20)
    at EmberAddon.<anonymous> (/localdisk/workspace/ember-frost-core/node_modules/ember-cli/lib/broccoli/ember-app.js:413:15)
    at Array.filter (native)

**Comment by rwjblue** [comment]
Current `release` **is** `0947bfc341b42cd2a121e5fde8b82aa54c1865a7` (see branch here: https://github.com/emberjs/ember.js/commits/release).  I believe that ember-try is operating correctly here.  

I believe this is an issue with https://github.com/emberjs/ember.js/commit/a61e6a9829fe00bd97b35814831b906afefb8966, which was cherry picked from https://github.com/emberjs/ember.js/pull/13239.  Can you open this issue on emberjs/ember.js?
