### ISSUE TITLE
Does `ember-try-config` need to be a dev dependency?

### ISSUE THREAD

**Issue by nbrookie** [ember-cli/ember-try#77]
Hey ember-try devs,

I ran into an issue when trying to install a package that relied on `ember-try` (see below). 
Does the `ember-try-config` package need to be a dependency for `ember-try`?

The following is taken from this issue: https://github.com/sir-dunxalot/ember-google-charts/issues/22

```
$ ember install ember-google-charts                          
Cannot find module 'ember-try-config'
Error: Cannot find module 'ember-try-config'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/me/dev/frontend/node_modules/ember-cli/node_modules/ember-try/lib/utils/config.js:7:34)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I was able to install `ember-google-charts` by doing the following:

```
$ npm install ember-try-config
(...snip...)
$ ember install ember-google-charts
```

My current setup is:
- ember-cli 2.6.1
- npm 5.4.1

**Comment by rwjblue** [comment]
> Does the ember-try-config package need to be a dependency for ember-try?

Yep, that is why it is listed here: https://github.com/ember-cli/ember-try/blob/master/package.json#L63

**Comment by nbrookie** [comment]
Ah, got it. Thx @rwjblue. Maybe this is an issue with `ember-google-charts` specifying an old version of `ember-try` in their `package.json`? They are currently specifying `0.0.6`.

**Comment by kategengler** [comment]
Anybody seen this lately?
